"""empty message

Revision ID: 69ff6e24a019
Revises: 
Create Date: 2021-08-10 17:40:16.410160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ff6e24a019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divvy')
    # ### end Alembic commands ###
