"""empty message

Revision ID: 812df7762abd
Revises: 69ff6e24a019
Create Date: 2021-08-10 17:45:54.245005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812df7762abd'
down_revision = '69ff6e24a019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divvy', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('divvy', sa.Column('birthday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('divvy', 'birthday')
    op.drop_column('divvy', 'gender')
    # ### end Alembic commands ###
